permalink: pretty
theme: jekyll_patternbot
patternbot:
  title: "Pen and Paper"
  description: |
    A Canadian stationery company who is passionate about design. From calendars to notebooks to desk decor, we have it all!
  font_url: "https://fonts.googleapis.com/css?family=Ibarra+Real+Nova:400,400i,700|Montserrat:400,500,700&display=swap"
  colors:
    accent: "--color-primary"
  rationales:
    typefaces.primary: |
      Ibarra Real Nova was selected because it is a simple, serif font that's easy to read. It is to be mainly used for body copy.
    typefaces.secondary: |
      Montserrat was selected because it's a classy, sans-serif font who thinner weight contrasts well with the primary font. It is to be used for headings, buttons, banners, etc.
    colors.primary: |
      The primary colours are dusty roses which give the website a chic, mature look. They should be used for most headings and as a highlight colour.
    colors.secondary: |
      The secondary colour is a charcoal grey that adds contrast to the site and should be used for body copy and certain headings.
