permalink: pretty
theme: jekyll_patternbot
patternbot:
  title: "Pen & Paper"
  description: |
  A Canadian stationery company who's passionate about design. From calendars to notebooks to desk decor, we have it all!
  font_url: "href="https://fonts.googleapis.com/css?family=Ibarra+Real+Nova:400,400i,700|Montserrat:400,500,700&display=swap"
  rationales:
