title: "Buttons"
description: |
  Buttons should be used in situations where a dramatic, obvious action is required. Try not to over use buttons because they should be the primary call-to-action for a screen.

patterns:
  basic:
    fields:
      - name: text
        type: string
        example: "Shop Now"
      - name: url
        type: url
        example: "/products/"
    title: "Basic"
    description: |
      Default to using the basic button.
    width: "12em"
  ghost:
    fields:
      - name: text
        type: string
        example: "See collection"
      - name: url
        type: url
        example: "/products/"
    title: "Ghost"
    description: |
      The ghost button is specifically for banners, where it will be placed in front of busy images.
  twitter:
    title: "Twitter"
    description: |
      The Twitter button is used to link the organization's Twitter account. It will be placed in the footer of every page.
  facebook:
    title: "Facebook"
    description: |
      The Facebook button is used to link the organization's Facebook account. It will be placed in the footer of every page.
  instagram:
    title: "Instagram"
    description: |
      The Instagram button is used to link the organization's Instagram account. It will be placed in the footer of every page.
  profile:
    title: "Profile"
    description: |
      The profile button is used to bring the user to their profile when they are logged in so they can adjust their account setttings. If they aren't logged in, it will bring them to sign up/login page. It will be placed in the main navigation.
  search:
    title: "Search"
    description: |
      When pressed, a search bar will show up to allow the user to search the website for any keywords. It will be placed in the main navigation.
  cart:
    title: "Cart"
    description: |
      The cart button is used to bring the user to their cart so they can see what they are about to purchase. It will be placed in the main navigation.
