title: "Sections"
description: |
  Different sections are created to give users information on different things such as a product or the company. They are used all throughout the website.

patterns:
    product-details:
      title: "Product Details"
      description: |
        The product details list is to be used on the product page to display all the details and features of each product.
      padding: 0 2em
    text-section:
      fields:
        - name: heading
          type: string
          example: "About Us"
        - name: text
          type: string
          example: "Pen & Paper was founded in Ottawa, Ontario in 2020. Our team is passionate about design and knows how important it is to stay organized. With that being said, we decided to help the world stay organized while being in style at the same time! We put our heart and soul into every design we create and we hope you can tell."
      title: "Text Section"
      description: |
        The text section is used anywhere that needs a chunk of text. It's used to give the user more in depth information about something such as the company's background. It may sometimes be paired with a button that links to another page.
    product-info:
      title: "Product Info"
      description: |
        The product info section is used on the product's page to show the name, price and description of the item.
    image:
      fields:
        - name: image
          type: string
          example: "sectional-banner-photo.jpg"
      title: "Image Section"
      description: |
        The image section is used whenever an image needs to be placed without any text or buttons on top of it. It could be used to divide sections on a page.
    cart:
      title: "Cart"
      description: |
        The cart section is used on the cart page to show the name, photo and price of the items that the user currently has in their cart. It also allows users to see their total and to remove any items from their cart.
      fields:
        - name: heading
          type: string
          example: "Small 2020 Planner"
        - name: price
          type: string
          example: $15
        - name: shipping
          type: string
          example: $15
        - name: total
          type: string
          example: $15
        - name: image
          example: "planner.jpg"

    order-summary:
      title: "Order Summary"
      description: |
        The order summary section is used on the checkout page to show the user what they are purchasing. Its purpose is to summarize their purchases so they can easily view everything they're buying.
      fields:
        - name: heading
          type: string
          example: "Small 2020 Planner"
        - name: price
          type: string
          example: $15
        - name: image
          example: "planner.jpg"
