title: "Banner"
description: |
  Banners should be used at the top of a website page to add imagery to the site. They can also be used as a call to action to get the users to purchase the products sold.

patterns:
  call-to-action-banner:
    fields:
      - name: heading
        type: string
        example: "Stylish and affordable"
      - name: text
        type: string
        example: "Everything you need to stay organized"
      - name: button_text
        type: string
        example: "Shop now"
        required: false
      - name: button_url
        type: url
        example: "/products/"
        required: false
      - name: image
        type: string
        example: "sectional-banner-photo.jpg"

    title: "Call to action"
    description: |
      Default to using the basic button. It should always be used in front of light backgrounds.
